### ISSUE TITLE
JSON log formats

### ISSUE THREAD

**Issue by sabrogden** [sergey-su/logjoint#2]
Are there any examples of how to handle log files in JSON format.  I've handled xml logging data using style sheets, anything similar in JSON.

An example log file from the library, serilog, https://github.com/serilog/serilog

{"@t":"2018-03-12T17:38:56.9682884Z","@i":"4b4159b6","@m":"data 1"}
{"@t":"2018-03-12T17:38:59.8813726Z","@i":"5a81f2ad","@m":"data 2\r\nline2"}

I would want the time from @t and the data from @m, and possible more tags in the future.

thanks
scott

**Comment by sergey-su** [comment]
The the moment there is no special support for Json similar to Xml support. Mainly because there is no widely accepted Json transformation language with .Net implementation.

Json with fixed structure can be easily parsed as text using regexps. Example you posted seems to have fixed structure.

For NLog JsonLayout there is a wizard that generates regexps-based text parser.
<img width="718" alt="screen shot 2018-05-07 at 20 31 39" src="https://user-images.githubusercontent.com/29118443/39718154-bfa8d3e8-5235-11e8-87cd-0930b0c0f827.png">

Sorry for delayed response

**Comment by sergey-su** [comment]
Hi @sabrogden 

A new update is published that contains JSON support. It includes a wizard to help describe custom JSON format. It uses [JUST.net](https://github.com/WorkMaze/JUST.net) for JSON transformations.

Serilog JSON format description is not included out-of-box because full semantic logging support is quite hard. But you can describe simple version of Serilog JSON format in new wizard. Or get Serilog JSON description I created - [Serilog - Compact JSON.format.xml.zip](https://github.com/sergey-su/logjoint/files/2043028/Serilog.-.Compact.JSON.format.xml.zip). Extract it to `c:\Users\...\AppData\Local\LogJoint\bin\Formats\` (`~/Applications/logjoint.app/Contents/MonoBundle/Formats/` on mac).

**Comment by sabrogden** [comment]
Tried this out in the latest and it looks good, I was able to load JSON files successfully.  Except I don't want to use the latest without the filtering Rules (https://github.com/sergey-su/logjoint/issues/9)
